CREATE TABLE Team (
    TEAM_ID INTEGER PRIMARY KEY,
    CITY TEXT CHECK(LENGTH(CITY) <= 15),
    NICKNAME TEXT CHECK(LENGTH(NICKNAME) <= 15),
    ABBREVIATION TEXT CHECK(LENGTH(ABBREVIATION) <= 4),
    STADIUM_TYPE TEXT, -- Dome, outdoor, etc. 
    STATE TEXT CHECK(LENGTH(STATE) <= 25),
    DIVISION TEXT CHECK(LENGTH(STATE) <= 8)
);

CREATE TABLE Player (
    PLAYER_ID INTEGER PRIMARY KEY,
    TEAM_ID INTEGER,
    FIRST_NAME TEXT CHECK(LENGTH(FIRST_NAME) <= 30),
    LAST_NAME TEXT CHECK(LENGTH(LAST_NAME) <= 30),
    IR_STATUS INTEGER,  -- BOOLEAN can be represented as INTEGER (0 for false, 1 for true)
    AGE INTEGER,
    POSITION TEXT CHECK(LENGTH(POSITION) <= 2),
    FOREIGN KEY (TEAM_ID) REFERENCES Team(TEAM_ID)
);

CREATE TABLE Game (
    GAME_ID INTEGER PRIMARY KEY,
    HOME_TEAM_ID INTEGER,
    AWAY_TEAM_ID INTEGER,
    WINNING_TEAM_ID INTEGER,
    SEASON_ID TEXT,
    GAME_DATE TEXT,  -- DATE can be stored as TEXT in 'YYYY-MM-DD' format
    GAME_TIME TEXT,  -- TIME can be stored as TEXT in 'HH:MM' format (EST)
    PRIMETIME INTEGER,  -- BOOLEAN can be represented as INTEGER (0 for false, 1 for true)
    FINAL_SCORE_HOME INTEGER,
    FINAL_SCORE_AWAY INTEGER,
    WEATHER TEXT,
    FOREIGN KEY (HOME_TEAM_ID) REFERENCES Team(TEAM_ID),
    FOREIGN KEY (AWAY_TEAM_ID) REFERENCES Team(TEAM_ID),
    FOREIGN KEY (WINNING_TEAM_ID) REFERENCES Team(TEAM_ID)
);

CREATE TABLE Player_Game_Stats (
    PLAYER_GAME_ID INTEGER PRIMARY KEY,
    PLAYER_ID INTEGER,
    GAME_ID INTEGER,
    HOME_TEAM_ID INTEGER,
    AWAY_TEAM_ID INTEGER,
    SEASON_ID TEXT,
    RUSHING_YARDS INTEGER,
    RECEIVING_YARDS INTEGER,
    PASS_YARDS INTEGER,
    CARRIES INTEGER,
    TARGETS INTEGER,
    RECEPTIONS INTEGER,
    PASS_ATTEMPTS INTEGER,
    PASS_COMPLETIONS INTEGER,
    FUMBLES INTEGER,
    INTERCEPTIONS INTEGER,
    RUSHING_TDS INTEGER,
    RECEIVING_TDS INTEGER,
    PASSING_TDS INTEGER,
    TARGET_SHARE REAL,
    CARRIES_SHARE REAL,
    TWO_PT_CNVS_RUSH INTEGER,
    TWO_PT_CNVS_REC INTEGER,
    TWO_PT_CNVS_PASS INTEGER,
    HOME_LEAGUE_PTS REAL,
    DK_PTS REAL,
    FD_PTS REAL,
    FOREIGN KEY (PLAYER_ID) REFERENCES Player(PLAYER_ID),
    FOREIGN KEY (GAME_ID) REFERENCES Game(GAME_ID),
    FOREIGN KEY (HOME_TEAM_ID) REFERENCES Team(TEAM_ID),
    FOREIGN KEY (AWAY_TEAM_ID) REFERENCES Team(TEAM_ID)
);

CREATE TABLE Team_Game_Stats (
    TEAM_GAME_ID INTEGER PRIMARY KEY,
    TEAM_ID INTEGER,
    HOME_TEAM_ID INTEGER,
    AWAY_TEAM_ID INTEGER,
    GAME_ID INTEGER,
    SEASON_ID TEXT,
    TOTAL_OFF_RUSH_YARDS INTEGER,
    TOTAL_OFF_REC_YARDS INTEGER,
    TOTAL_OFF_PASS_YARDS INTEGER,
    TOTAL_OFF_YARDS INTEGER,
    TOTAL_OFF_PTS INTEGER,
    TOTAL_DEF_RUSH_YARDS INTEGER,
    TOTAL_DEF_REC_YARDS INTEGER,
    TOTAL_DEF_PASS_YARDS INTEGER,
    TOTAL_DEF_YARDS INTEGER,
    TOTAL_DEF_PTS INTEGER,
    FRIEND_LEAGUE_QB_PTS_ALLOWED REAL,
    FRIEND_LEAGUE_RB_PTS_ALLOWED REAL,
    FRIEND_LEAGUE_WR_PTS_ALLOWED REAL,
    FRIEND_LEAGUE_TE_PTS_ALLOWED REAL,
    DK_QB_PTS_ALLOWED REAL,
    DK_RB_PTS_ALLOWED REAL,
    DK_WR_PTS_ALLOWED REAL,
    DK_TE_PTS_ALLOWED REAL,
    FD_QB_PTS_ALLOWED REAL,
    FD_RB_PTS_ALLOWED REAL,
    FD_WR_PTS_ALLOWED REAL,
    FD_TE_PTS_ALLOWED REAL,
    FOREIGN KEY (TEAM_ID) REFERENCES Team(TEAM_ID),
    FOREIGN KEY (GAME_ID) REFERENCES Game(GAME_ID),
    FOREIGN KEY (HOME_TEAM_ID) REFERENCES Team(TEAM_ID),
    FOREIGN KEY (AWAY_TEAM_ID) REFERENCES Team(TEAM_ID)
);