-- Query inserts all 32 NFL teams into Teams tabel in nfl database
INSERT INTO Team (TEAM_ID, CITY, NICKNAME, ABBREVIATION, STADIUM_TYPE, STATE, DIVISION) VALUES
(1, 'Arizona', 'Cardinals', 'ARI', 'Retractable', 'AZ', 'NFC West'),
(2, 'Atlanta', 'Falcons', 'ATL', 'Retractable', 'GA', 'NFC South'),
(3, 'Baltimore', 'Ravens', 'BAL', 'Outdoor', 'MD', 'AFC North'),
(4, 'Buffalo', 'Bills', 'BUF', 'Outdoor', 'NY', 'AFC East'),
(5, 'Carolina', 'Panthers', 'CAR', 'Outdoor', 'NC', 'NFC South'),
(6, 'Chicago', 'Bears', 'CHI', 'Outdoor', 'IL', 'NFC North'),
(7, 'Cincinnati', 'Bengals', 'CIN', 'Outdoor', 'OH', 'AFC North'),
(8, 'Cleveland', 'Browns', 'CLE', 'Outdoor', 'OH', 'AFC North'),
(9, 'Dallas', 'Cowboys', 'DAL', 'Retractable', 'TX', 'NFC East'),
(10, 'Denver', 'Broncos', 'DEN', 'Outdoor', 'CO', 'AFC West'),
(11, 'Detroit', 'Lions', 'DET', 'Dome', 'MI', 'NFC North'),
(12, 'Green Bay', 'Packers', 'GB', 'Outdoor', 'WI', 'NFC North'),
(13, 'Houston', 'Texans', 'HOU', 'Retractable', 'TX', 'AFC South'),
(14, 'Indianapolis', 'Colts', 'IND', 'Retractable', 'IN', 'AFC South'),
(15, 'Jacksonville', 'Jaguars', 'JAX', 'Outdoor', 'FL', 'AFC South'),
(16, 'Kansas City', 'Chiefs', 'KC', 'Outdoor', 'MO', 'AFC West'),
(17, 'Las Vegas', 'Raiders', 'LV', 'Dome', 'NV', 'AFC West'),
(18, 'Los Angeles', 'Chargers', 'LAC', 'Dome', 'CA', 'AFC West'),
(19, 'Los Angeles', 'Rams', 'LAR', 'Dome', 'CA', 'NFC West'),
(20, 'Miami', 'Dolphins', 'MIA', 'Outdoor', 'FL', 'AFC East'),
(21, 'Minnesota', 'Vikings', 'MIN', 'Dome', 'MN', 'NFC North'),
(22, 'New England', 'Patriots', 'NE', 'Outdoor', 'MA', 'AFC East'),
(23, 'New Orleans', 'Saints', 'NO', 'Dome', 'LA', 'NFC South'),
(24, 'New York', 'Giants', 'NYG', 'Outdoor', 'NJ', 'NFC East'),
(25, 'New York', 'Jets', 'NYJ', 'Outdoor', 'NJ', 'AFC East'),
(26, 'Philadelphia', 'Eagles', 'PHI', 'Outdoor', 'PA', 'NFC East'),
(27, 'Pittsburgh', 'Steelers', 'PIT', 'Outdoor', 'PA', 'AFC North'),
(28, 'San Francisco', '49ers', 'SF', 'Outdoor', 'CA', 'NFC West'),
(29, 'Seattle', 'Seahawks', 'SEA', 'Outdoor', 'WA', 'NFC West'),
(30, 'Tampa Bay', 'Buccaneers', 'TB', 'Outdoor', 'FL', 'NFC South'),
(31, 'Tennessee', 'Titans', 'TEN', 'Outdoor', 'TN', 'AFC South'),
(32, 'Washington', 'Commanders', 'WAS', 'Outdoor', 'MD', 'NFC East');