-- Drop the existing PlayerGameStats table if it exists
DROP TABLE IF EXISTS PlayerGameStats;

-- Create the new PlayerGameStats table
CREATE TABLE PlayerGameStats (
    GAMELOG_ID INTEGER PRIMARY KEY,
    SEASON_ID TEXT CHECK(LENGTH(SEASON_ID) <= 8),
    PLAYER_ID INTEGER,
    GAME_ID INTEGER,
    MATCHUP TEXT CHECK(LENGTH(MATCHUP) <= 15),
    WL TEXT CHECK(LENGTH(WL) <= 1),
    MIN INTEGER,
    FGM INTEGER,
    FGA INTEGER,
    FG_PCT FLOAT,
    FG3M INTEGER,
    FG3A INTEGER,
    FG3_PCT FLOAT,
    FTM INTEGER,
    FTA INTEGER,
    FT_PCT FLOAT,
    OREB INTEGER,
    DREB INTEGER,
    REB INTEGER,
    AST INTEGER,
    STL INTEGER,
    BLK INTEGER,
    TOV INTEGER,
    PF INTEGER,
    PTS INTEGER,
    PLUS_MINUS INTEGER,
    GAME_TYPE TEXT CHECK(LENGTH(GAME_TYPE) <= 15),
    HOME_TEAM INTEGER,
    AWAY_TEAM INTEGER,
    FOREIGN KEY (PLAYER_ID) REFERENCES Player(PLAYER_ID),
    FOREIGN KEY (GAME_ID) REFERENCES Game(GAME_ID),
    FOREIGN KEY (HOME_TEAM) REFERENCES Team(TEAM_ID),
    FOREIGN KEY (AWAY_TEAM) REFERENCES Team(TEAM_ID)
);
